version: "3.9"

services:
  db:
    container_name: db_hw30
    image: postgres:14.7-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: api_db
      POSTGRES_USER: api_user
      POSTGRES_PASSWORD: api_pass
    restart: always
    ports:
      - "5433:5432"

volumes:
  postgres_data: